// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Protos/HydrologyControl.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ControlService.Protos {
  public static partial class HydrologyControlService
  {
    static readonly string __ServiceName = "HydrologyControlService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.CreateRequest> __Marshaller_CreateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.CreateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.CreateResponse> __Marshaller_CreateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.CreateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.DeleteRequest> __Marshaller_DeleteRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.DeleteRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.DeleteResponse> __Marshaller_DeleteResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.DeleteResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.GetRequest> __Marshaller_GetRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.GetRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.GetResponse> __Marshaller_GetResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.GetResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.UpdateRequest> __Marshaller_UpdateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.UpdateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.UpdateResponse> __Marshaller_UpdateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.UpdateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.CheckValueRequest> __Marshaller_CheckValueRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.CheckValueRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.CheckValueResponse> __Marshaller_CheckValueResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.CheckValueResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.GetDateRequest> __Marshaller_GetDateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.GetDateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.GetDateResponse> __Marshaller_GetDateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.GetDateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.GateIntervalRequest> __Marshaller_GateIntervalRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.GateIntervalRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::ControlService.Protos.GateIntervalResponse> __Marshaller_GateIntervalResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::ControlService.Protos.GateIntervalResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ControlService.Protos.CreateRequest, global::ControlService.Protos.CreateResponse> __Method_Create = new grpc::Method<global::ControlService.Protos.CreateRequest, global::ControlService.Protos.CreateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Create",
        __Marshaller_CreateRequest,
        __Marshaller_CreateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ControlService.Protos.DeleteRequest, global::ControlService.Protos.DeleteResponse> __Method_Delete = new grpc::Method<global::ControlService.Protos.DeleteRequest, global::ControlService.Protos.DeleteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delete",
        __Marshaller_DeleteRequest,
        __Marshaller_DeleteResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ControlService.Protos.GetRequest, global::ControlService.Protos.GetResponse> __Method_Get = new grpc::Method<global::ControlService.Protos.GetRequest, global::ControlService.Protos.GetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Get",
        __Marshaller_GetRequest,
        __Marshaller_GetResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ControlService.Protos.UpdateRequest, global::ControlService.Protos.UpdateResponse> __Method_Update = new grpc::Method<global::ControlService.Protos.UpdateRequest, global::ControlService.Protos.UpdateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Update",
        __Marshaller_UpdateRequest,
        __Marshaller_UpdateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ControlService.Protos.CheckValueRequest, global::ControlService.Protos.CheckValueResponse> __Method_CheckValue = new grpc::Method<global::ControlService.Protos.CheckValueRequest, global::ControlService.Protos.CheckValueResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CheckValue",
        __Marshaller_CheckValueRequest,
        __Marshaller_CheckValueResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ControlService.Protos.GetDateRequest, global::ControlService.Protos.GetDateResponse> __Method_GetDate = new grpc::Method<global::ControlService.Protos.GetDateRequest, global::ControlService.Protos.GetDateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDate",
        __Marshaller_GetDateRequest,
        __Marshaller_GetDateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::ControlService.Protos.GateIntervalRequest, global::ControlService.Protos.GateIntervalResponse> __Method_GateInterval = new grpc::Method<global::ControlService.Protos.GateIntervalRequest, global::ControlService.Protos.GateIntervalResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GateInterval",
        __Marshaller_GateIntervalRequest,
        __Marshaller_GateIntervalResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ControlService.Protos.HydrologyControlReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HydrologyControlService</summary>
    [grpc::BindServiceMethod(typeof(HydrologyControlService), "BindService")]
    public abstract partial class HydrologyControlServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ControlService.Protos.CreateResponse> Create(global::ControlService.Protos.CreateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ControlService.Protos.DeleteResponse> Delete(global::ControlService.Protos.DeleteRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ControlService.Protos.GetResponse> Get(global::ControlService.Protos.GetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ControlService.Protos.UpdateResponse> Update(global::ControlService.Protos.UpdateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ControlService.Protos.CheckValueResponse> CheckValue(global::ControlService.Protos.CheckValueRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ControlService.Protos.GetDateResponse> GetDate(global::ControlService.Protos.GetDateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::ControlService.Protos.GateIntervalResponse> GateInterval(global::ControlService.Protos.GateIntervalRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(HydrologyControlServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Create, serviceImpl.Create)
          .AddMethod(__Method_Delete, serviceImpl.Delete)
          .AddMethod(__Method_Get, serviceImpl.Get)
          .AddMethod(__Method_Update, serviceImpl.Update)
          .AddMethod(__Method_CheckValue, serviceImpl.CheckValue)
          .AddMethod(__Method_GetDate, serviceImpl.GetDate)
          .AddMethod(__Method_GateInterval, serviceImpl.GateInterval).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HydrologyControlServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Create, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ControlService.Protos.CreateRequest, global::ControlService.Protos.CreateResponse>(serviceImpl.Create));
      serviceBinder.AddMethod(__Method_Delete, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ControlService.Protos.DeleteRequest, global::ControlService.Protos.DeleteResponse>(serviceImpl.Delete));
      serviceBinder.AddMethod(__Method_Get, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ControlService.Protos.GetRequest, global::ControlService.Protos.GetResponse>(serviceImpl.Get));
      serviceBinder.AddMethod(__Method_Update, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ControlService.Protos.UpdateRequest, global::ControlService.Protos.UpdateResponse>(serviceImpl.Update));
      serviceBinder.AddMethod(__Method_CheckValue, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ControlService.Protos.CheckValueRequest, global::ControlService.Protos.CheckValueResponse>(serviceImpl.CheckValue));
      serviceBinder.AddMethod(__Method_GetDate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ControlService.Protos.GetDateRequest, global::ControlService.Protos.GetDateResponse>(serviceImpl.GetDate));
      serviceBinder.AddMethod(__Method_GateInterval, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ControlService.Protos.GateIntervalRequest, global::ControlService.Protos.GateIntervalResponse>(serviceImpl.GateInterval));
    }

  }
}
#endregion
